export const NAVSHOW = 'NAVSHOW';
export const MENULIST = 'MENULIST';
export const SETTINGSHOW = 'SETTINGSHOW';
export const DEFAULTMENUKEYS = 'DEFAULTMENUKEYS';
export const LANGUAGE = 'LANGUAGE';

export const GETCURRENCY = 'GETCURRENCY';

export const FINDREWARDLIST = 'FINDREWARDLIST';
